---
# NumPy 

NumPy is a powerful linear algebra library for Python. Pretty much all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks.

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In [1]:
import numpy as np

NumPy has many built-in functions and capabilities.

## NumPy Arrays

NumPy arrays essentially come in two types: `vectors` and `matrices`.
- Vectors are strictly 1-dimensional (1D) arrays
- Matrices are 2D (but you should note a matrix can still have only one row or one column).

## Why use Numpy array? Why not just a list?

There are lot's of reasons to use a Numpy array instead of a "standard" python list object.
- Memory Efficiency of Numpy Array vs list
- Easily expands to N-dimensional objects
- Speed of calculations of numpy array
- Broadcasting operations and functions with numpy
- All the data science and machine learning libraries we use are built with Numpy

## Simple Example of what numpy array can do

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


---
## Creating NumPy Arrays from Objects

### From a Python List
Create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods to create arrays

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [20]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random 
Ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [22]:
np.random.rand(2)

array([0.2370848 , 0.63425063])

In [23]:
np.random.rand(5,5)

array([[0.83218927, 0.94822628, 0.2030413 , 0.06526184, 0.24566761],
       [0.34346728, 0.67445144, 0.70491304, 0.16732591, 0.25565012],
       [0.5500725 , 0.03354247, 0.36353236, 0.96723061, 0.98396979],
       [0.00832149, 0.73757265, 0.05836448, 0.06558725, 0.87645061],
       [0.41340446, 0.31292529, 0.98729907, 0.80781633, 0.4565806 ]])

### randn
<font color=red>Returns a sample (or samples) from the "standard normal" distribution [σ = 1], values closer to zero are more likely to appear. Unlike **rand** which is uniform.</font>
[[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

<img src= 'pictures/normal_vs_uniform.png' width=500/> 

Image source: https://thatascience.com/learn-numpy/normal-vs-uniform/

In [24]:
np.random.randn(2)

array([ 1.24765682, -0.62286825])

In [25]:
np.random.randn(5,5)

array([[ 0.26772403,  0.56552377,  0.64425151, -2.02539832,  0.40915913],
       [ 1.07456582, -0.91317315,  0.37835787,  0.09308721,  1.08383321],
       [-1.7318582 , -1.58806311,  1.87275342, -0.925583  ,  1.16332911],
       [ 0.25760199, -0.91446005,  0.2446671 , -0.17907718,  0.28375002],
       [ 0.90313594, -1.14166896, -0.56666497, -0.11671337, -0.51872619]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [26]:
np.random.randint(1,100)

90

In [27]:
np.random.randint(1,100,10)

array([71,  6, 62, 83, 78, 74, 83, 89,  1, 36])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

---
## Array Attributes and Methods

Some useful attributes and methods for an array:

In [30]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

- Finding max or min values
- Find their index locations using argmin or argmax

In [32]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [33]:
ranarr.max()

39

In [34]:
ranarr.argmax()

7

In [35]:
ranarr.min()

2

In [36]:
ranarr.argmin()

9

### Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [37]:
# Vector
arr.shape

(25,)

In [41]:
# Notice the two sets of brackets, row vector
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
arr.reshape(1, 25).shape

(1, 25)

In [43]:
# Column vector
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [45]:
arr.dtype

dtype('int64')

In [46]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')