---
# NumPy 

NumPy is a powerful linear algebra library for Python. Pretty much all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks.

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Basics notes of NumPy.

In [1]:
import numpy as np

NumPy has many built-in functions and capabilities.

## NumPy Arrays

NumPy arrays essentially come in two flavors: `vectors` and `matrices`. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

## Why use Numpy array? Why not just a list?

There are lot's of reasons to use a Numpy array instead of a "standard" python list object.
- Memory Efficiency of Numpy Array vs list
- Easily expands to N-dimensional objects
- Speed of calculations of numpy array
- Broadcasting operations and functions with numpy
- All the data science and machine learning libraries we use are built with Numpy

## Simple Example of what numpy array can do

In [3]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [4]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


---
## Creating NumPy Arrays from Objects

### From a Python List
Create an array by directly converting a list or list of lists:

In [5]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods to create arrays

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [15]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random 
Ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [17]:
np.random.rand(2)

array([0.71088095, 0.80548975])

In [18]:
np.random.rand(5,5)

array([[0.45193627, 0.97251727, 0.17658779, 0.01973921, 0.09293234],
       [0.94953893, 0.72413386, 0.49095191, 0.37485906, 0.56963344],
       [0.81115219, 0.18229932, 0.41092442, 0.24095835, 0.8487428 ],
       [0.91006422, 0.36436489, 0.34312929, 0.77611145, 0.59323826],
       [0.82693688, 0.85654619, 0.97409671, 0.33227536, 0.34373514]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [19]:
np.random.randn(2)

array([0.61760391, 1.530165  ])

In [20]:
np.random.randn(5,5)

array([[-0.57074411, -0.7226852 ,  0.67943875, -2.0631334 ,  0.30452566],
       [ 0.88964538, -1.20146315, -1.02458214, -2.96744861, -0.5506581 ],
       [ 1.82202692, -0.59807932, -0.57881676,  0.22871995,  0.85020392],
       [ 0.50333837,  0.2440732 ,  0.28503731,  1.08877586,  1.65037254],
       [ 0.12000363, -0.54839084, -1.2869864 ,  1.24964298, -1.10999458]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [23]:
np.random.randint(1,100)

37

In [33]:
np.random.randint(1,100,10)

array([68, 55, 14, 92, 74, 63, 88, 67, 80, 75])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

---
## Array Attributes and Methods

Some useful attributes and methods for an array:

In [44]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

- Finding max or min values
- Find their index locations using argmin or argmax

In [45]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [46]:
ranarr.max()

43

In [47]:
ranarr.argmax()

3

In [48]:
ranarr.min()

1

In [49]:
ranarr.argmin()

1

### Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [50]:
# Vector
arr.shape

(25,)

In [51]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
arr.reshape(1,25).shape

(1, 25)

In [53]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')