# NumPy: Indexing and Selection

How to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
# Creating sample array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
Similar to python lists:

In [3]:
# Get a value at an index
arr[8]

8

In [5]:
# Get values in a range (slice)
arr[1:5]

array([1, 2, 3, 4])

### Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That means that if you want to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [6]:
# Setting a value with index range
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
# Reset array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# an slice of an array is an array
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
# Change Slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

The changes also occur in our original array, the data is not copied

In [10]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
# Explicit copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

The general format is `arr_2d[row][col]` or `arr_2d[row, col]`

In [12]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [14]:
arr_2d[1, 0]

20

In [15]:
# 2D array slicing
# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [16]:
# Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [17]:
# Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### More Indexing Help

<img src= 'pictures/numpy_indexing.png' width=500/>

Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

### Conditional Selection

In [18]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [21]:
# Selection based on boolean
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])