# NumPy: Operations

### Arithmetic

*array with array* arithmetic, or *scalar with array* arithmetic.

In [1]:
import numpy as np

arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# This will raise a Warning on division by zero, nan (Not A Number)
arr / arr

/var/folders/qr/7hbtnxs12w3_8072fbvf78kc0000gn/T/ipykernel_84295/829665983.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
# Also a warning (but not an error) relating to infinity
1 / arr

/var/folders/qr/7hbtnxs12w3_8072fbvf78kc0000gn/T/ipykernel_84295/3242981687.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array Functions

[reference](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>

In [8]:
# Square Root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
# Exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
# Trigonometric Functions, sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
# Natural Logarithm
new_arr = np.arange(1, 5)
np.log(new_arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### Summary Statistics on Arrays

Common summary statistics like:
- sum
- mean
- max

In [12]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(f'Sum:{arr.sum()} Mean:{arr.mean()} Max:{arr.max()}')

Sum:45 Mean:4.5 Max:9


<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

### Axis Logic
With 2-dimensional arrays (matrices), consider `rows` and `columns`.

In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

In [14]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

<tt>axis=0</tt>, imply returning an array of sums along the vertical axis, <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='pictures/axis_logic.png' width=400/>

In [16]:
print(arr_2d)
print(f'The Array has, rows={arr_2d.shape[0]} columns:{arr_2d.shape[1]}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The Array has, rows=3 columns:4


In [17]:
# Getting a vector
print(arr_2d.sum(axis=1))
print(arr_2d.sum(axis=1).shape)

[10 26 42]
(3,)
